[package]
name = "null"
version = "0.1.0"
edition = "2021"

[dependencies]
strum = { version = "0.26.3", features = ["derive"] }
# nasm-to-string={ path="crates/nasm" }
# lazy_static = { version = "1.4.0", features = [] }
